DROP DATABASE IF EXISTS Multiplayer_Game_DB;
CREATE DATABASE IF NOT EXISTS Multiplayer_Game_DB;

USE Multiplayer_Game_DB;

CREATE TABLE IF NOT EXISTS Users(
    userId INT(10) PRIMARY KEY AUTO_INCREMENT NOT NULL,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    `password` VARCHAR(150) NOT NULL,
    token VARCHAR(50) DEFAULT NULL
)
ENGINE=INNODB;